const {chromium}=require('playwright');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=__dirname;
const base='http://127.0.0.1:4327';
const results={checked_at:new Date().toISOString(),scope:'Synthetic visual prototype only',checks:[],errors:[],screenshots:[]};
const check=(name,passed,detail)=>{results.checks.push({name,passed,detail});assert.ok(passed,name+': '+JSON.stringify(detail));};
let browser;
(async()=>{
 browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});
 page.on('pageerror',e=>results.errors.push(e.message));
 const external=[];page.on('request',r=>{if(!r.url().startsWith(base))external.push(r.url());});
 const save=async(name,fullPage=false)=>{await page.screenshot({path:path.join(root,name+'.png'),fullPage});results.screenshots.push(name+'.png');};
 await page.goto(base);
 check('Preview disclosure visible',await page.getByText('Fictional data · Refresh to reset').isVisible());
 await page.getByRole('button',{name:'Complete Movement & strength',exact:true}).click();
 check('Completion awards 25 XP',await page.locator('[data-xp]').textContent()==='105 XP');
 await page.getByRole('button',{name:'Undo Movement & strength',exact:true}).click();
 check('Undo restores sample XP',await page.locator('[data-xp]').textContent()==='80 XP');
 await page.getByRole('button',{name:'Enable calm mode'}).click();
 check('Calm mode hides game summary',!(await page.locator('.level-card').isVisible()));
 await page.getByRole('button',{name:'Disable calm mode'}).click();
 await page.getByRole('button',{name:'Quick capture',exact:true}).click();
 await page.locator('#capture-title').fill('<img src=x onerror=alert(1)>');
 await page.getByRole('button',{name:'Add to planning inbox',exact:true}).click();
 check('User text rendered inertly',await page.getByText('<img src=x onerror=alert(1)>',{exact:true}).isVisible()&&await page.locator('main img').count()===0);
 await page.getByRole('button',{name:'Move',exact:true}).click();
 check('Move is unapplied before acceptance',await page.locator('[data-portfolio-time]').textContent()==='10:00');
 await page.getByRole('button',{name:'Keep current plan',exact:true}).click();
 check('Cancelled move leaves time intact',await page.locator('[data-portfolio-time]').textContent()==='10:00');
 await page.getByRole('button',{name:'Move',exact:true}).click();
 await page.getByRole('button',{name:'Accept move',exact:true}).click();
 check('Accepted move changes time',await page.locator('[data-portfolio-time]').textContent()==='11:00');
 await page.getByRole('button',{name:'Import schedule',exact:true}).click();
 await page.getByRole('button',{name:'Preview calendar changes',exact:true}).click();
 check('Import requires timezone',!(await page.locator('dialog').evaluate(d=>d.open)));
 await page.locator('#import-zone').selectOption('America/Denver');
 await page.getByRole('button',{name:'Preview calendar changes',exact:true}).click();
 check('Import excludes ambiguous deadline',await page.locator('dialog').getByText(/1 ambiguous deadline excluded/).isVisible());
 await page.getByRole('button',{name:'Confirm and add seminar',exact:true}).click();
 check('Confirmed seminar appears once',await page.getByRole('heading',{name:'Research seminar',exact:true}).count()===1);
 await page.locator('#desktop-nav').getByRole('button',{name:'Train',exact:true}).click();
 await page.getByRole('button',{name:'Half a session counts',exact:true}).click();
 await page.getByRole('button',{name:'Finish sample session',exact:true}).click();
 await page.locator('#desktop-nav').getByRole('button',{name:'Today',exact:true}).click();
 check('Partial then full totals only 25 XP',await page.locator('[data-xp]').textContent()==='105 XP');
 await page.locator('#desktop-nav').getByRole('button',{name:'Fuel',exact:true}).click();
 await page.getByRole('button',{name:'Log your first sample meal',exact:true}).click();
 await page.getByRole('button',{name:'Save sample meal',exact:true}).click();
 check('Sample meal visible',await page.getByRole('heading',{name:'Vegetable & grain bowl',exact:true}).isVisible());
 await page.getByRole('button',{name:'Compare approaches',exact:true}).click();
 check('Diet comparison cards present',await page.locator('.diet-card').count()===9);
 await page.locator('.diet-card').filter({hasText:'OMAD'}).click();
 check('OMAD does not activate a prescription',await page.locator('dialog').getByText(/No target or fasting window is assigned/).isVisible());
 await page.keyboard.press('Escape');
 check('Escape closes dialog',!(await page.locator('dialog').evaluate(d=>d.open)));
 await page.getByRole('button',{name:'Shape your plan',exact:true}).click();
 await page.locator('[data-answer="goal"]').fill('Build a fictional portfolio');
 await page.getByRole('button',{name:'Continue →',exact:true}).click();
 await page.locator('[data-answer="minutes"]').selectOption('15 minutes');
 for(let i=0;i<3;i++)await page.getByRole('button',{name:'Continue →',exact:true}).click();
 await page.getByRole('button',{name:'Preview my plan',exact:true}).click();
 check('Onboarding reflects chosen time',(await page.locator('dialog .delta-row').textContent()).includes('15 minutes'));
 await page.getByRole('button',{name:'Use this sample day',exact:true}).click();
 check('Onboarding changes sample task duration',await page.getByText('15 min · from sample preferences',{exact:true}).isVisible());
 await page.getByRole('button',{name:'Settings & devices',exact:true}).click();
 await page.getByRole('button',{name:'Review',exact:true}).click();
 await page.getByRole('button',{name:'Keep 10:00',exact:true}).click();
 check('Sync conflict selection visible',await page.getByText('Sample conflict resolved',{exact:true}).isVisible());
 await page.clock.install();
 await page.goto(base+'/?view=train');
 await page.getByRole('button',{name:'Start timer',exact:true}).click();
 await page.clock.fastForward(121000);
 check('Timer stops at rest boundary',await page.locator('#timer-number').textContent()==='01:00');
 await page.getByRole('button',{name:'Start timer',exact:true}).click();
 await page.clock.fastForward(61000);
 await page.getByRole('button',{name:'Start timer',exact:true}).click();
 await page.clock.fastForward(121000);
 check('Timer ends after final round',await page.getByRole('button',{name:'Finished',exact:true}).isDisabled());
 await page.goto(base);
 const screenViews=['today','plan','train','fuel','growth','goals','review','weekly','onboarding','imports','settings'];
 for(const theme of ['night','marble','journal']){
   for(const [device,w,h] of [['desktop',1440,1050],['tablet',834,1112],['phone',390,844]]){
     await page.setViewportSize({width:w,height:h});
     for(const view of screenViews){
       await page.goto(`${base}/?theme=${theme}&view=${view}`);
       const layout=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,mainWidth:document.querySelector('main').getBoundingClientRect().width,headings:document.querySelectorAll('main h1').length,unnamed:[...document.querySelectorAll('button')].filter(b=>b.getBoundingClientRect().width>0&&!b.textContent.trim()&&!b.getAttribute('aria-label')).length}));
       check(`${theme}/${device}/${view}: layout and labels`,layout.scroll<=layout.width&&layout.headings===1&&layout.unnamed===0,layout);
       if((view==='today'||view==='train'||view==='weekly')&&device==='desktop')await save(`${theme}-${view}-desktop`,true);
       if(theme==='night'&&(view==='today'||view==='train'||view==='onboarding'||view==='imports')&&device!=='desktop')await save(`${theme}-${view}-${device}`,false);
     }
   }
 }
 await page.setViewportSize({width:320,height:740});await page.goto(base);
 check('320px Today no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto(base);
 check('Reduced motion CSS active',await page.evaluate(()=>getComputedStyle(document.querySelector('.toast')).transitionDuration==='0s'));
 await page.setViewportSize({width:1440,height:1050});await page.goto(base);
 await page.getByRole('button',{name:'Quick capture',exact:true}).focus();await page.keyboard.press('Enter');
 await page.keyboard.press('Tab');await page.keyboard.press('Tab');await page.keyboard.press('Tab');await page.keyboard.press('Tab');
 check('Keyboard focus stays inside modal',await page.evaluate(()=>document.querySelector('dialog').contains(document.activeElement)));
 await page.keyboard.press('Escape');
 check('Closing modal restores trigger focus',await page.getByRole('button',{name:'Quick capture',exact:true}).evaluate(b=>b===document.activeElement));
 check('No external requests',external.length===0,external);
 check('No JavaScript runtime errors',results.errors.length===0,results.errors);
 await browser.close();
 results.passed=true;
})().catch(e=>{results.passed=false;results.failure=e.stack;process.exitCode=1;}).finally(async()=>{if(browser&&browser.isConnected())await browser.close();fs.writeFileSync(path.join(root,'verification.json'),JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify({passed:results.passed,checks:results.checks.length,failure:results.failure,errors:results.errors,screenshots:results.screenshots.length},null,2));});
