export interface HealthSource { title: string; url: string; published: string | null; access?: string }
export interface DietCard { id: string; name: string; dimension: string; description: string; evidence: string; benefits: string; risks: string; adequacy: string; practical: string; training: string; guidance: string; recommendation: 'comparison' | 'education' | 'clinician'; reviewed: string; sources: HealthSource[] }
const source = (title: string, url: string, published: string | null = null, access = 'Reviewed source'): HealthSource => ({ title, url, published, access });
const niddk = source('NIDDK: choosing a weight-management program', 'https://www.niddk.nih.gov/health-information/weight-management/choosing-a-safe-successful-weight-loss-program');
const b12 = source('NIH: vitamin B12', 'https://ods.od.nih.gov/factsheets/VitaminB12-Consumer/');
const fasting = source('NIDDK: fasting safely with diabetes', 'https://www.niddk.nih.gov/health-information/professionals/diabetes-discoveries-practice/fasting-safely-with-diabetes', null);
const nice = source('NICE NG246: diet and activity', 'https://www.nice.org.uk/guidance/ng246/chapter/Physical-activity-and-diet', null, 'Prior Phase 1 review; page retrieval failed in this refresh');
function card(id: string, name: string, dimension: string, description: string, evidence: string, benefits: string, risks: string, adequacy: string, practical: string, training: string, guidance: string, sources: HealthSource[], recommendation: DietCard['recommendation'] = 'comparison'): DietCard {
  return { id, name, dimension, description, evidence, benefits, risks, adequacy, practical, training, guidance, sources, recommendation, reviewed: '2026-10-04' };
}
export const diets: DietCard[] = [
  card('balanced', 'Balanced eating', 'Food selection', 'Varied foods matched to preferences, access and needs.', 'Public-health guidance; no single menu guarantees a physique.', 'Flexible habits can support consistency.', 'A restrictive version can still underfuel.', 'Review variety and adequate total intake.', 'Flexible budget and preparation options.', 'Leave room for training fuel and recovery.', 'Adapt allergies and clinician instructions.', [niddk]),
  card('mediterranean', 'Mediterranean-style', 'Food selection', 'Plant-forward meals with legumes, whole grains, olive oil and other varied foods.', 'Cardiovascular trial evidence applies to studied populations; it is not an abs forecast.', 'A useful framework for diet quality.', 'Energy intake and individual tolerance still matter.', 'Include adequate protein and varied nutrient sources.', 'Batch cooking and frozen ingredients can improve practicality.', 'Adapt portions to training and recovery.', 'Review personal restrictions before major changes.', [source('Mediterranean diet trial evidence', 'https://pubmed.ncbi.nlm.nih.gov/29897866/', '2018', 'Prior Phase 1 abstract review')]),
  card('protein', 'Higher-protein eating', 'Nutrient emphasis', 'Emphasizes adequate protein within a complete diet.', 'Sports-nutrition position stand; needs depend on individual circumstances.', 'Can support resistance-training adaptation.', 'More is not automatically better.', 'Protein does not replace fiber, fats or other nutrients.', 'Food choice affects cost; supplements are optional.', 'Coordinate intake with the full training day.', 'Discuss targets with a professional when health conditions affect protein needs.', [source('ISSN: protein and exercise', 'https://pubmed.ncbi.nlm.nih.gov/28642676/', '2017-06-20')]),
  card('vegetarian', 'Vegetarian', 'Food selection', 'Excludes meat; may include eggs and dairy.', 'Nutrient adequacy depends on actual food choices.', 'Can match ethical preferences and varied meals.', 'Low intake of reliable B12 sources can create a shortfall.', 'Plan B12 and protein sources; assess other nutrients.', 'Legumes and meal preparation can help affordability.', 'Protein sources and sufficient food matter.', 'Seek dietetic input if restrictions make adequacy difficult.', [b12]),
  card('vegan', 'Vegan', 'Food selection', 'Excludes animal-derived foods.', 'Food quality and nutrient planning matter; the label alone predicts little.', 'Can align eating with personal values.', 'B12 is not reliably supplied by unfortified plant foods.', 'Plan a reliable B12 source and assess overall adequacy.', 'Availability, labels and preparation affect adherence.', 'Plan varied protein and adequate intake.', 'Use qualified guidance for nutrient concerns or special health needs.', [b12]),
  card('low-carb', 'Low carbohydrate', 'Nutrient emphasis', 'Reduces carbohydrate without necessarily producing ketosis.', 'DIETFITS found no significant 12-month weight difference from its healthy low-fat comparator.', 'May fit some food preferences.', 'Large exclusions can make the plan hard to sustain.', 'Retain nutrient-rich foods and fiber.', 'Consider groceries, cooking and social meals.', 'Review energy and performance when changing fuel sources.', 'Medication or health constraints require individual review.', [source('DIETFITS randomized trial', 'https://pubmed.ncbi.nlm.nih.gov/29466592/', '2018-02-20')]),
  card('keto', 'Ketogenic', 'Nutrient emphasis', 'Very low carbohydrate intended to produce nutritional ketosis.', 'Not interchangeable with moderate low-carb eating; long-term suitability is not established for everyone.', 'Some people prefer its defined structure.', 'Restrictive food choices can conflict with heart-health guidance.', 'Review fiber, food quality and nutrient gaps.', 'Social meals and cost may limit adherence.', 'Monitor performance rather than assuming an advantage.', 'Discuss medical conditions and medications before attempting it.', [source('AHA: dietary-pattern alignment', 'https://professional.heart.org/en/science-news/popular-dietary-patterns-alignment-with-american-heart-association-2021-dietary-guidance/top-things-to-know', '2023-04-27')], 'education'),
  card('fasting', 'Intermittent fasting / time-restricted eating', 'Meal timing', 'Changes when eating occurs; protocols differ.', 'A 12-month trial found no added weight-loss benefit from its eating window over calorie restriction alone.', 'A timing preference may simplify routine.', 'Medication and glucose risks require attention.', 'A short window does not ensure adequate nutrition.', 'Fit meals around real obligations.', 'Avoid forcing sessions through poor energy or symptoms.', 'Get professional advice for diabetes, pregnancy, eating-disorder history or other relevant restrictions.', [source('Time-restricted eating trial', 'https://www.nejm.org/doi/pdf/10.1056/NEJMoa2114833', '2022-04-21'), fasting], 'education'),
  card('omad', 'One meal a day (OMAD)', 'Meal timing', 'Concentrates daily eating into one meal.', 'Small, short controlled studies do not establish long-term superiority or universal safety.', 'Some find a single meal convenient.', 'Hunger, tolerance and restricted opportunity to eat may be problematic.', 'Meeting nutritional needs in one meal can be difficult.', 'Consider family meals and work routines.', 'Check whether intake and energy support training.', 'Preference is not clearance; review medical, medication and food-tracking concerns first.', [source('Reduced meal frequency pilot', 'https://pubmed.ncbi.nlm.nih.gov/17413096/', '2007-04'), fasting], 'education'),
  card('carnivore', 'Carnivore', 'Food selection', 'Mostly or entirely animal foods, excluding most plant foods.', 'Self-selected survey evidence cannot establish causation or long-term safety.', 'Reported benefits are not proof of superiority.', 'Elevated LDL was reported in a subset; broader risks need study.', 'Fiber and nutrient adequacy need careful review.', 'Food costs and limited variety can be barriers.', 'No established training advantage from this survey.', 'Compare and log without treating it as a default recommendation.', [source('Carnivore survey, 2,029 adults', 'https://pubmed.ncbi.nlm.nih.gov/34934897/', '2021-11-02')], 'education'),
  card('clear-liquid', 'Medical clear liquids', 'Medical diet', 'Clear fluids under procedure- or condition-specific instructions.', 'Clinical-use guidance, not a general fat-loss strategy.', 'May serve a specified medical purpose.', 'Inappropriate as an unsupervised long-term diet.', 'Not a complete ordinary eating pattern.', 'Follow the exact permitted list and duration.', 'Training must follow the treating team’s instructions.', 'Use only with professional direction.', [source('MedlinePlus: clear liquid diet', 'https://www.medlineplus.gov/ency/patientinstructions/000205.htm', '2024-07-24', 'Source review date')], 'clinician'),
  card('full-liquid', 'Medical full liquids', 'Medical diet', 'Liquid foods beyond clear fluids; prescribed for specific circumstances.', 'Medical guidance is individualized.', 'May bridge a medical transition in eating.', 'Swallowing needs can require further texture rules.', 'Nutrient completeness is not automatic.', 'Follow the prescribed foods and duration.', 'Coordinate activity with the treating team.', 'Clinician or dietitian guidance is required.', [source('MedlinePlus: full liquid diet', 'https://www.medlineplus.gov/ency/patientinstructions/000206.htm')], 'clinician'),
  card('complete-replacement', 'Nutritionally complete meal replacements', 'Product / energy strategy', 'Specific formulated products, not every shake.', 'Evidence applies to the actual formulation and supported program.', 'Measured portions may simplify some programs.', 'Low-energy regimens need professional oversight.', 'Verify completeness and intended use on the product.', 'Compare cost, access and transition to meals.', 'Adequacy must fit activity and recovery.', 'Do not use an unreviewed liquid-only regimen.', [nice], 'clinician'),
  card('commercial-liquid', 'Commercial liquid weight-loss programs', 'Commercial program', 'Programs differ in products, intake and support.', 'An unnamed program cannot be rated as proven.', 'Convenience depends on the actual program.', 'Marketing claims and restrictions require scrutiny.', 'Check the product, dose and nutritional completeness.', 'Review full recurring cost and follow-up support.', 'Do not assume the program fuels training adequately.', 'Obtain program-specific evidence and appropriate clinical support.', [nice], 'clinician'),
];
export const healthSources = {
  resistance: source('ACSM resistance training guidance', 'https://www.acsm.org/wp-content/uploads/2026/03/Resistance-Training-Position-Stand-infographic.pdf', '2026-03'),
  boxing: source('England Boxing: home shadowboxing drills', 'https://www.englandboxing.org/news_articles/england-boxing-shadow-boxing-drills-week-three/', null),
  activity: source('CDC: adult activity guidance', 'https://www.cdc.gov/physical-activity-basics/guidelines/adults.html', null),
};
