import assert from 'node:assert/strict';
import { mkdtemp, readFile, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createServer } from 'node:net';
import { createHash } from 'node:crypto';
import { chromium } from 'playwright';
import sharp from 'sharp';
import { buildDesktop } from './build-desktop.mjs';

const run = promisify(execFile);
const root = await mkdtemp(resolve(tmpdir(), 'stoic-desktop-test-'));
const { folder } = await buildDesktop({ outputRoot: root, archive: false });
const files = await readdir(folder, { recursive: true });
assert.ok(files.includes('server.cjs') && files.includes('runtime\\node.exe'));
assert.ok(!files.some(file => /sqlite|(^|[\\/])private|\.env/i.test(file)));
const manifest = JSON.parse(await readFile(resolve(folder, 'manifest.json'), 'utf8'));
assert.equal(manifest.runtime, 'v24.19.0');
assert.ok(manifest.files.length>=24);
assert.ok(manifest.files.some(f=>f.path==='apps/local-pilot/public/setup.js'));
assert.ok(manifest.files.some(f=>f.path==='apps/local-pilot/public/goal-visualization.js'));
for(const f of manifest.files.filter(f=>f.path.startsWith('node_modules/')))assert.match(f.path,/^node_modules\/(sharp\/|@img\/(sharp-win32-x64|colour)\/|detect-libc\/|semver\/)/);
for (const file of manifest.files) assert.equal(createHash('sha256').update(await readFile(resolve(folder, file.path))).digest('hex'), file.sha256);
const listener = createServer();
await new Promise(done => listener.listen(0, '127.0.0.1', done));
const port = listener.address().port;
await new Promise(done => listener.close(done));
const url = `http://127.0.0.1:${port}`;
const env = { ...process.env, STOIC_BODY_DATA_DIR: resolve(root, 'test-data'), STOIC_BODY_PORT: String(port) };
await run('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',resolve(folder,'install.ps1'),'-InstallRoot',resolve(root,'installed'),'-ShortcutDirectory',resolve(root,'desktop'),'-NoLaunch'],{env,timeout:30000});
const shortcut=await run('powershell.exe',['-NoProfile','-Command',"$s=(New-Object -ComObject WScript.Shell).CreateShortcut($env:STOIC_TEST_SHORTCUT); @{target=$s.TargetPath;arguments=$s.Arguments;workingDirectory=$s.WorkingDirectory;icon=$s.IconLocation} | ConvertTo-Json -Compress"],{env:{...env,STOIC_TEST_SHORTCUT:resolve(root,'desktop','Stoic Body.lnk')}});
const installed=JSON.parse(shortcut.stdout);assert.ok(installed.target.endsWith('powershell.exe')&&installed.arguments.includes('launch.ps1')&&installed.arguments.includes('-WindowStyle Hidden'));assert.ok(installed.workingDirectory.startsWith(resolve(root,'installed')));
assert.ok(installed.icon.includes('assets\\brand\\stoic-body.ico'));
console.log('PASS: verified per-user installation and real Windows desktop shortcut.');
const launch = (...args) => run('powershell.exe', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', resolve(folder, 'launch.ps1'), ...args], { env, timeout: 30000 });
const browser = await chromium.launch({ headless: true });
try {
  const starts=await Promise.allSettled([launch('-NoBrowser'),launch('-NoBrowser'),launch('-NoBrowser')]);
  assert.deepEqual(starts.map(s=>s.status),['fulfilled','fulfilled','fulfilled'],'simultaneous starts must share one owned server');
  console.log('PASS: bundled launcher starts the local service.');
  assert.equal((await (await fetch(`${url}/api/identity`)).json()).product, 'Stoic Body');
  const icon=await fetch(`${url}/favicon.ico`);assert.equal(icon.status,200);assert.equal(icon.headers.get('content-type'),'image/x-icon');assert.equal(Buffer.from(await icon.arrayBuffer()).readUInt16LE(4),7);
  assert.deepEqual(await (await fetch(`${url}/api/bootstrap`)).json(), { authenticated: false, mode: 'local' });
  const page = await browser.newPage();
  await page.goto(url);
  await page.getByRole('button', { name: 'Create my account', exact: true }).click();
  await page.getByLabel('Your name').fill('New client');
  await page.getByLabel('Username', { exact: true }).fill('new-client');
  await page.getByLabel('Passphrase', { exact: true }).fill('new client test passphrase');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await page.locator('#recovery-key').waitFor();
  await page.getByRole('button', { name: 'I saved my key — continue' }).click();
  await page.getByRole('heading', { name: /Welcome, New client/ }).waitFor();
  console.log('PASS: clean welcome and new-client signup.');
  await launch('-NoBrowser'); // Re-opening must reuse this installation, not create another server.
  await launch('-Stop');
  await assert.rejects(fetch(`${url}/api/bootstrap`));
  await launch('-NoBrowser');
  const login = await fetch(`${url}/api/auth/login`, { method: 'POST', headers: { Origin: url, 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'new-client', password: 'new client test passphrase' }) });
  assert.equal(login.status, 200);
  const state = await login.json();
  assert.equal(state.account.displayName, 'New client');
  assert.equal(state.snapshot.goals.length, 0);
  assert.equal(Object.keys(state.snapshot.answers).length, 0);
  const image=await sharp({create:{width:8,height:8,channels:3,background:'#ccc'}}).png().toBuffer();
  const photoHeaders={Origin:url,'Content-Type':'application/json',Cookie:login.headers.get('set-cookie').split(';')[0],'X-Stoic-Token':state.token};
  const upload=await fetch(url+'/api/photos/add',{method:'POST',headers:photoHeaders,body:JSON.stringify({kind:'source',image:image.toString('base64'),consent:true,uploadId:'packaged-decoder-test'})});
  assert.equal(upload.status,200,await upload.text());
  await launch('-Stop');await launch('-NoBrowser');
  const relogin=await fetch(url+'/api/auth/login',{method:'POST',headers:{Origin:url,'Content-Type':'application/json'},body:JSON.stringify({username:'new-client',password:'new client test passphrase'})}),reopened=await relogin.json();
  const photos=await fetch(url+'/api/photos',{headers:{Cookie:relogin.headers.get('set-cookie').split(';')[0],'X-Stoic-Token':reopened.token}});assert.equal((await photos.json()).photos.length,1);
  console.log('PASS: bundled native photo decoder executes and private photo survives restart.');
  console.log('PASS: allowlisted Windows bundle, real launcher, fresh account, isolated data, stop and restart.');
} finally {
  await browser.close();
  await launch('-Stop');
  // Only this freshly-created test bundle; clean a failed ownership-race probe too.
  await run('powershell.exe',['-NoProfile','-Command',"Get-CimInstance Win32_Process | Where-Object { $_.ExecutablePath -eq $env:STOIC_TEST_RUNTIME } | ForEach-Object { Stop-Process -Id $_.ProcessId }"],{env:{...env,STOIC_TEST_RUNTIME:resolve(folder,'runtime/node.exe')}});
}

