import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve, dirname, basename } from 'node:path';
import { startPilot } from '../apps/local-pilot/server';

async function run() {
  const dir = mkdtempSync(join(tmpdir(), 'stoic-browser-'));
  const pilot = await startPilot({ databasePath: join(dir, 'pilot.sqlite'), port: 0 });
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, timezoneId: 'America/Denver' });
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const checks: string[] = [];
  const check = (name: string, value: unknown) => { assert.ok(value, name); checks.push(name); };
  const evidence = resolve('docs/evidence/phase-4/local-pilot'); mkdirSync(evidence, { recursive: true });
  page.setDefaultTimeout(5000);
  try {
    await page.goto(pilot.url); await page.getByText('Nothing scheduled yet.', { exact: true }).waitFor();
    check('empty account starts with zero XP', await page.locator('#total-xp').textContent() === '0 XP');
    await page.getByRole('button', { name: 'Goals', exact: true }).click();
    await page.getByLabel('Goal title', { exact: true }).fill('Learn <img src=x onerror=alert(1)>');
    await page.getByLabel('Why it matters').fill('A synthetic software test');
    await page.getByRole('button', { name: 'Save goal', exact: true }).click();
    await page.getByText('Learn <img src=x onerror=alert(1)>', { exact: true }).first().waitFor();
    check('user markup renders as text', await page.locator('#goal-list img').count() === 0);
    await page.getByLabel('Task title', { exact: true }).fill('Movement practice');
    await page.getByLabel('Action type').selectOption('workout');
    await page.getByLabel('Linked goal').selectOption({ label: 'Learn <img src=x onerror=alert(1)>' });
    await page.getByRole('button', { name: 'Save task', exact: true }).click();
    await page.getByText('Movement practice', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Plan', exact: true }).click();
    await page.getByLabel('Planning date').fill('2026-10-05');
    await page.getByLabel('Timezone', { exact: true }).fill('America/Denver');
    await page.getByRole('button', { name: 'Preview schedule', exact: true }).click();
    await page.getByRole('heading', { name: 'Review your day' }).waitFor();
    await page.getByRole('button', { name: 'Accept schedule', exact: true }).click();
    await page.getByRole('button', { name: 'Today', exact: true }).click();
    await page.getByRole('button', { name: 'Half done', exact: true }).click();
    await page.locator('#total-xp').filter({ hasText: '12 XP' }).waitFor(); check('half completion grants 12 XP', true);
    await page.getByRole('button', { name: 'Complete', exact: true }).click();
    await page.locator('#total-xp').filter({ hasText: '25 XP' }).waitFor();
    await page.reload(); await page.locator('#total-xp').filter({ hasText: '25 XP' }).waitFor(); check('completion survives browser reload', true);
    await page.getByLabel('Selected date').fill('2026-10-05');
    await page.getByRole('button', { name: 'Undo completion', exact: true }).waitFor();
    await page.screenshot({ path: join(evidence, 'desktop.png'), fullPage: true });
    await page.getByRole('button', { name: 'Undo completion', exact: true }).click();
    await page.locator('#total-xp').filter({ hasText: '0 XP' }).waitFor(); check('correction reverses exactly the award', true);
    await page.getByRole('button', { name: 'Profile', exact: true }).click();
    await page.getByLabel('Question').selectOption('health');
    await page.getByRole('button', { name: 'Skip this question' }).click();
    await page.getByText('Saved: skipped', { exact: true }).waitFor();
    await page.reload(); await page.getByRole('button', { name: 'Profile', exact: true }).click(); await page.getByLabel('Question').selectOption('health');
    await page.getByText('Saved: skipped', { exact: true }).waitFor(); check('onboarding answers survive reload', true);
    await page.getByRole('button', { name: 'Settings', exact: true }).click();
    await page.getByRole('button', { name: 'Light', exact: true }).click();
    check('theme setting applies', await page.locator('html').getAttribute('data-mode') === 'light');
    await page.reload(); check('theme setting survives reload', await page.locator('html').getAttribute('data-mode') === 'light');
    await page.getByRole('button', { name: 'Settings', exact: true }).click(); await page.getByRole('button', { name: 'Dark', exact: true }).click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Today', exact: true }).click(); await page.getByLabel('Selected date').fill('2026-10-05');
    check('mobile layout has no horizontal overflow', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: join(evidence, 'mobile.png'), fullPage: true });
    await page.route('**/api/command', route => route.abort('internetdisconnected'));
    await page.getByRole('button', { name: 'Complete', exact: true }).click();
    await page.getByText('Could not reach the local app. Check that it is running, then retry.', { exact: true }).waitFor();
    check('failed request does not display an earned award', await page.locator('#total-xp').textContent() === '0 XP');
    await page.unroute('**/api/command');
    await page.getByRole('button', { name: 'Retry save', exact: true }).click();
    await page.locator('#total-xp').filter({ hasText: '25 XP' }).waitFor(); check('retry recovers the same operation', true);
    await page.getByRole('button', { name: 'Undo completion', exact: true }).click();
    await page.getByRole('button', { name: 'Protect session', exact: true }).click();
    await page.getByRole('button', { name: 'Unlock session', exact: true }).waitFor();
    check('protected session has no move action', await page.getByRole('button', { name: 'Move session', exact: true }).count() === 0);
    await page.getByRole('button', { name: 'Unlock session', exact: true }).click();
    await page.getByRole('button', { name: 'Move session', exact: true }).click();
    await page.getByLabel('Session date and time').fill('2026-10-05T09:00');
    await page.getByRole('button', { name: 'Preview session time', exact: true }).click();
    await page.getByRole('button', { name: 'Confirm session time', exact: true }).click();
    await page.getByRole('button', { name: 'Today', exact: true }).click();
    await page.getByText(/9:00 AM–9:30 AM · 0% complete/).waitFor(); check('session move is previewed and saved', true);
    await page.getByRole('button', { name: 'Goals', exact: true }).click();
    await page.getByRole('button', { name: 'Edit task', exact: true }).click();
    await page.getByLabel('Task title', { exact: true }).fill('Movement revised');
    await page.getByRole('button', { name: 'Save task', exact: true }).click();
    await page.getByText('Movement revised', { exact: true }).waitFor(); check('task title edits persist', true);
    await page.getByRole('button', { name: 'Archive task', exact: true }).click();
    await page.getByRole('button', { name: 'Restore task', exact: true }).waitFor();
    await page.getByRole('button', { name: 'Restore task', exact: true }).click();
    await page.getByRole('button', { name: 'Archive task', exact: true }).waitFor(); check('task archive and restore preserve the record', true);
    await page.getByLabel('Task title', { exact: true }).fill('Read later');
    await page.getByRole('button', { name: 'Save task', exact: true }).click();
    await page.getByText('Read later', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Profile', exact: true }).click();
    await page.getByLabel('Question').selectOption('time'); await page.getByLabel('Your answer').fill('10:00–11:00');
    await page.getByRole('button', { name: 'Save answer', exact: true }).click();
    await page.getByText('Saved: answered', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Plan', exact: true }).click();
    check('saved availability changes planning inputs', await page.getByLabel('Available from').inputValue() === '10:00' && await page.getByLabel('Available until').inputValue() === '11:00');
    await page.getByRole('button', { name: 'Preview schedule', exact: true }).click();
    await page.getByRole('button', { name: 'Accept schedule', exact: true }).click();
    await page.getByRole('button', { name: 'Undo schedule', exact: true }).first().click();
    await page.getByText('Schedule undone', { exact: true }).waitFor(); check('an untouched accepted schedule can be undone', true);
    await page.keyboard.press('Tab'); check('keyboard can reach an interactive control', await page.evaluate(() => document.activeElement?.tagName !== 'BODY'));
    check('no browser runtime errors', errors.length === 0);
    writeFileSync(join(evidence, 'browser-checks.json'), JSON.stringify({ at: new Date().toISOString(), checks, errors }, null, 2));
    console.log(`${checks.length} browser checks passed.`);
  } finally {
    await browser.close(); await pilot.close();
    const target = resolve(dir); assert.equal(dirname(target), resolve(tmpdir())); assert.ok(basename(target).startsWith('stoic-browser-'));
    rmSync(target, { recursive: true, force: true });
  }
}
run().catch(error => { console.error(error); process.exitCode = 1; });
